### ISSUE TITLE
Depth related multi-view consistency

### ISSUE THREAD

**Issue by dogyoonlee** [oppo-us-research/NeuLF#1]
Hello, I appreciate to your awesome work and public code!

However, there are no code for multi-view consistency related to scene depth information in your paper section 3.3.

Is your code still under construction?

**Comment by lizhong3232** [comment]
Thank you for your interest in our work. Our goal now is to release an initial framework that is simple yet effective and to share with the community how it functions. Additionally, we have plans to release a more advanced framework for multiview consistency in the future.
